Month 12/step 1
frrenzy/algososh pull request #1
Opened 2023-02-27 01:51 UTC by frrenzy

2023-02-27 05:44 UTC, andryxxa93 requested changes
Здравствуйте! Работа проделана огромная!
Что понравилось:
- Отлично типизировали проект
- Хорошо сделаны классы
- Хорошо сделали визуализацию

Однако есть пару моментов, которые необходимо поправить:
- По заданию все кнопки сабмита должны быть неактивными, если в инпуте ничего нет.
- Связный список не работает. При нажатии кнопок появляется лоадер, но ничего не происходит. 

Исправьте, пожалуйста, недочеты и работа будет принята. Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-02-27 21:26 UTC, frrenzy commented
A можно доп инфы, где список не работает? протестировал на винде 10, линуксе (на базе убунту 22.04) и маке в файрфоксе и хроме, все ок. Вот видео для примера: https://drive.google.com/file/d/1_1D3EEEosB7XCFDBJoNScDEwj0Bj38jd/view?usp=share_link

2023-02-27 21:39 UTC, frrenzy commented
Пока добавил фикс для отключения кнопочек

2023-02-28 13:13 UTC, andryxxa93 commented
> A можно доп инфы, где список не работает, пожалуйста? Протестировал на винде 10, линуксе (на базе убунту 22.04) и макосе 13.2.1 в файрфоксе и хроме последниъ версий, все ок. Вот видео для примера: https://drive.google.com/file/d/1_1D3EEEosB7XCFDBJoNScDEwj0Bj38jd/view?usp=share_link Как видно, ветка нужная и никаких изменений после последнего коммита нет

Вот так не работает. Возможно проблема с моей стороны. 
https://user-images.githubusercontent.com/60173362/221864325-fd162055-7a9e-4857-8592-fc236f4f2c97.mov

2023-02-28 13:14 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-02-28 13:16 UTC, frrenzy commented
> Супер, вы отлично поработали! Поздравляю! Работа принята. Желаю удачного продолжения обучения!
 я имел в виду, какая у вас операционка и браузер? повторю конфигурацию, покопаюсь поподробнее

2023-02-28 13:27 UTC, merged